insert into currency_spread_percentage (id,symbol,spread_percentage) values (1,'AED',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (2,'AFN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (3,'ALL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (4,'AMD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (5,'ANG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (6,'AOA',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (7,'ARS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (8,'AUD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (9,'AWG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (10,'AZN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (11,'BAM',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (12,'BBD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (13,'BDT',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (14,'BGN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (15,'BHD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (16,'BIF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (17,'BMD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (18,'BND',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (19,'BOB',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (20,'BRL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (21,'BSD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (22,'BTC',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (23,'BTN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (24,'BWP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (25,'BYN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (26,'BYR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (27,'BZD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (28,'CAD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (29,'CDF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (30,'CHF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (31,'CLF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (32,'CLP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (33,'CNY',6.00);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (34,'COP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (35,'CRC',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (36,'CUC',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (37,'CUP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (38,'CVE',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (39,'CZK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (40,'DJF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (41,'DKK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (42,'DOP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (43,'DZD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (44,'EGP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (45,'ERN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (46,'ETB',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (47,'EUR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (48,'FJD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (49,'FKP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (50,'GBP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (51,'GEL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (52,'GGP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (53,'GHS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (54,'GIP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (55,'GMD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (56,'GNF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (57,'GTQ',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (58,'GYD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (59,'HKD',3.25);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (60,'HNL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (61,'HRK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (62,'HTG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (63,'HUF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (64,'IDR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (65,'ILS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (66,'IMP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (67,'INR',4.50);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (68,'IQD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (69,'IRR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (70,'ISK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (71,'JEP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (72,'JMD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (73,'JOD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (74,'JPY',3.25);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (75,'KES',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (76,'KGS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (77,'KHR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (78,'KMF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (79,'KPW',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (80,'KRW',3.25);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (81,'KWD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (82,'KYD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (83,'KZT',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (84,'LAK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (85,'LBP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (86,'LKR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (87,'LRD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (88,'LSL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (89,'LTL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (90,'LVL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (91,'LYD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (92,'MAD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (93,'MDL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (94,'MGA',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (95,'MKD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (96,'MMK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (97,'MNT',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (98,'MOP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (99,'MRO',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (100,	'MUR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (101,	'MVR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (102,	'MWK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (103,	'MXN',4.50);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (104,	'MYR',4.50);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (105,	'MZN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (106,	'NAD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (107,	'NGN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (108,	'NIO',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (109,	'NOK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (110,	'NPR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (111,	'NZD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (112,	'OMR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (113,	'PAB',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (114,	'PEN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (115,	'PGK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (116,	'PHP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (117,	'PKR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (118,	'PLN',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (119,	'PYG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (120,	'QAR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (121,	'RON',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (122,	'RSD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (123,	'RUB',6.00);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (124,	'RWF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (125,	'SAR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (126,	'SBD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (127,	'SCR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (128,	'SDG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (129,	'SEK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (130,	'SGD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (131,	'SHP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (132,	'SLE',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (133,	'SLL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (134,	'SOS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (135,	'SRD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (136,	'STD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (137,	'SVC',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (138,	'SYP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (139,	'SZL',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (140,	'THB',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (141,	'TJS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (142,	'TMT',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (143,	'TND',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (144,	'TOP',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (145,	'TRY',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (146,	'TTD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (147,	'TWD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (148,	'TZS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (149,	'UAH',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (150,	'UGX',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (151,	'USD', 0.0);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (152,	'UYU',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (153,	'UZS',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (154,	'VEF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (155,	'VES',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (156,	'VND',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (157,	'VUV',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (158,	'WST',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (159,	'XAF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (160,	'XAG',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (161,	'XAU',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (162,	'XCD',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (163,	'XDR',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (164,	'XOF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (165,	'XPF',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (166,	'YER',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (167,	'ZAR',6.00);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (168,	'ZMK',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (169,	'ZMW',2.75);
insert into currency_spread_percentage (id,symbol,spread_percentage) values (170,	'ZWL',2.75);
